Repository stelligent/mu, pull requests merged in 2018-09, with the labels that each got.

#325 Issue 258 - Validation
  Gopkg.lock
  Gopkg.toml
  cli/app.go
  cli/app_test.go
  cli/validate.go
  cli/validate_test.go
  common/context.go
  common/context_test.go
  common/types.go
  common/validate.go
  common/validate_test.go
  workflows/environment_upsert.go
  workflows/pipeline_upsert.go
  workflows/service_deploy.go
Labels: in progress

#330 Correctly warn if program version unparsable
  provider/aws/cloudformation.go
Labels: bug

#331 Decompose upsert method to be less complex
  Makefile
  common/extension.go
  common/strings.go
  provider/aws/cloudformation.go
  provider/aws/init.go
  provider/aws/s3.go
  provider/aws/s3_test.go
  workflows/cwlogs_view.go
  workflows/database_params.go
  workflows/database_upsert.go
  workflows/database_upsert_test.go
  workflows/environment_normalize.go
  workflows/environment_upsert.go
  workflows/environment_upsert_test.go
  workflows/pipeline_upsert.go
  workflows/service_deploy.go
  workflows/service_push.go
Labels: core
